version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  
  - package-ecosystem: "cargo"
    directory: "/src-tauri/"
    schedule:
      interval: "monthly"
